application: slack-five
version: 1-1
runtime: python27
api_version: 1
threadsafe: true

handlers:

- url: .*
  script: main.app
  secure: always

librariers:
- name: webapp2
  version: "2.5.1"
- name: jinja2
  version: latest
- name: ssl
  version: "latest"     
